### ISSUE TITLE
API function `findContained` fails if called immediately when a template is created due to the canvas element not having finished drawing

### ISSUE THREAD

**Issue by SirGarhi** [krbz999/templatemacro#9]
I've been unable to work out why but the MeasuredTemplate.shape property is coming back undefined, breaking the call to the contains function.

I assume the other api functions are broken in the same way but haven't tried them.

**Comment by thatlonelybugbear** [comment]
Try adding a small delay before actually calling the `findContained` API method.
```js
await new Promise(w => setTimeout(w,  250));
```

**Comment by SirGarhi** [comment]
That worked great, even with setting the delay to 1 it was enough.

**Comment by krbz999** [comment]
They should work just fine unless you call them immediately using a template that is being created. This is a core issue, as the MeasuredTemplate being drawn on the canvas and the MeasuredTemplateDocument being created are two separate calls. Template Macro requires both to be completed. The only fix (as this will not be fixed in core) is to wait manually in your script if you call this API method in the 'when created' trigger. I cannot add the fix to the API method itself, as that would turn it async.
